<p>Welcome to Rich Pleasure Resources. Your privacy is important to us.&nbsp;<br />Rich Pleasure Resources and its affiliates ("Rich Pleasure", "us", "our" or "we") are dedicated to protecting the privacy rights of our users ("users" or "you"). This Privacy Policy (the "Policy") describes the ways we collect, use, and manage the information, including personal information, that you provide or we collect in connection with our application and websites, www.kutw4u.com, (the "Site") or any.&nbsp;</p>
<p><br />By using the Service and the Site, you are expressing your agreement to this Policy and the processing of your data, including your personal information, in the manner provided in this Policy. If you do not agree to these terms, please do not use the Service.&nbsp;</p>
<h3>Information Collection and Use</h3>
<p><br />Rich Pleasure Resources collects information as described below. Rich Pleasure Resources's primary goals in collecting and using information is to create your account, provide Services to you, improve our Service, contact you, conduct research and create reports for internal use.&nbsp;<br />If you wish to submit a resume, we provide you the option to upload it to the site and we collect your name, email address and mobile telephone number. We use this information to contact you regarding setting up an interview or to determine if you are qualified for the position in which you applied.&nbsp;</p>
<h3>Rich Pleasure Resources 's Sites</h3>
<p><br />While you are browsing Rich Pleasure Resources's Sites, your computer's operating system, Internet Protocol (IP) address, access times, browser type and language and referring Web site addresses may be logged automatically. We may use this information to monitor, develop and analyze your use of the Service. In addition, we may ask you to submit and we may process data that is personal to you, including but not limited to your name, profile photo, gender, age or birthday, links to your profiles on social networking websites and other third party sites, user names and e-mail and mail addresses. We may use this information to create a user profile and provide you services. We may use your email address to contact you about your experience with Rich Pleasure&nbsp;Sites and notify you about company news and promotions. Your gender and birthday may be used to analyze user trends and target certain promotions. Your mail address may be used if we have merchandise or other physical promotional materials that we want to send to you. If you no longer wish to receive these types of promotional materials, you may opt-out from receiving them at any time by click on unsubscribe.&nbsp;</p>
<h3>Social Media (Features) and Widgets</h3>
<p><br />Our Web site includes Social Media Features, such as the Facebook Like button and Widgets, such as the Share this button or interactive mini-programs that run on our site. These Features may collect your IP address, which page you are visiting on our site, and may set a cookie to enable the Feature to function properly. Social Media Features and Widgets are either hosted by a third party or hosted directly on our Site. Your interactions with these Features are governed by the privacy policy of the company providing it.&nbsp;</p>
<p>&nbsp;</p>
<h3>Facebook Connect</h3>
<p>You can log in to our site using sign-in services ("SN Service") such as Facebook Connect, LinkedIn, or an Open ID provider. These services will authenticate your identity and provide you the option to share certain personal information with us such as your name, email address, and resume to pre-populate our sign up form. Services like Facebook Connect give you the option to post information about your activities on this Web site to your profile page to share with others within your network.&nbsp;<br />We may collect and record information through the SN Service in accordance with the policies and terms of that SN Service. The information we collect when you connect your user account to an SN Service may include: (1) your name, (2) your SN Service user identification number and/or user name, (3) locale, city, state and country, (4) sex, (5) birth date, (6) email address, (7) profile picture or its URL, and (8) the SN Service user identification numbers for your friends that are also connected to Rich Pleasure Resources's application(s).&nbsp;</p>
<h3>Invite a Friend</h3>
<p><br />Rich Pleasure Resources may offer you the opportunity to invite your contacts from a SN Service (such as your Facebook friends) so that those contacts can be located in Rich Pleasure Resources application and/or you can invite them to join you in Rich Pleasure Resources&nbsp;service. Such contact information will be used only for the purpose of sending communications to the addressee.&nbsp;</p>
<h3>Customer Service</h3>
<p><br />We may collect your email address when you contact our customer service group and we may use that email address to contact you about your experience with Site and Service and notify you about company news and promotions&nbsp;</p>
<h3>Push Notifications</h3>
<p><br />We may occasionally send you push notifications through our mobile applications to send you updates, high scores and other service related notifications that may be of importance to you. You may at any time opt-out from receiving these types of communications by turning them off at the device level through your settings.&nbsp;</p>
<h3>Other Collection</h3>
<p><br />We may also acquire information from you through (1) your access and participation in message boards on the Service, (2) your participation in surveys regarding the Service or (3) your participation in a sweepstakes or contest through the Service.&nbsp;<br />We may provide you the opportunity to participate in a sweepstakes or contest through our Service. If you participate, we will request certain personal information from you. Participation in these sweepstakes and contests are voluntary and you therefore have a choice whether or not to disclose this information. The requested information typically includes contact information (such as name and shipping address), and demographic information (such as zip code).&nbsp;<br />We use this information to notify winners and award prizes, to monitor traffic or personalize the Service. We may use a third party service provider to conduct these sweepstakes or contests; that company is prohibited from using your users' personal information for any other purpose.&nbsp;</p>
<h3>Tracking Technologies</h3>
<p><br />We and our marketing and outsourcing partners, affiliates, or analytics service providers use technologies such as cookies, beacons, scripts, and tags to identify a user's computer/device and to "remember" things about your visit, such as your preferences or a user name and password. Information contained in a cookie may be linked to your personal information, such as your user ID, for purposes such as improving the quality of our Services, tailoring recommendations to your interests, and making the Service easier to use. You can disable cookies at any time, although you may not be able to access or use features of the Service.&nbsp;<br />We may feature advertisements served by third parties that deliver cookies to your computer/device so the content you access and advertisements you see can be tracked. Since the third party advertising companies associate your computer/device with a number, they will be able to recognize your computer/device each time they send you an advertisement. These advertisers may use information about your visits to our Service and third party sites and applications in order to measure advertisement performance and to provide advertisements about goods and services of interest to you. This Policy does not apply to, and we are not responsible for the data collection practices of these third party advertisers, and we encourage you to check their privacy policies to learn more about their use of cookies and other technology.&nbsp;</p>
<p>&nbsp;</p>
<h3>Third Party Services</h3>
<p><br />Our services may contain third party tracking tools from our service providers. Such third parties may use cookies, APIs, and SDKs in our services to enable them to collect and analyze user information on our behalf. The third parties may have access to information such as your device identifier, MAC address, IMEI, locale (specific location where a given language is spoken), geo-location information, and IP address for the purpose of providing their services under their respective privacy policies. Our privacy policy does not cover the use of tracking tools from third parties. We do not have access or control over these third parties.&nbsp;</p>
<h3>Ad Networks</h3>
<p><br />We may feature advertising within our Service. The advertisers may collect and use information about you, such as your Service session activity, device identifier, MAC address, IMEI, geo-location information and IP address. They may use this information to provide advertisements of interest to you.&nbsp;</p>
<h3>How We Use Information</h3>
<p><br />We use information collected through our Service for purposes described in this Policy or disclosed to you in connection with our Service. For example, we may use your information to:&nbsp;<br />1) create accounts and allow users to used our service;&nbsp;<br />2) identify and suggest connections with other users;&nbsp;<br />3) operate and improve our Service;&nbsp;<br />4) understand you and your preferences to enhance your experience and enjoyment using our Service;&nbsp;<br />5) respond to your comments and questions and provide customer service;&nbsp;<br />6) provide and deliver products and services you request;&nbsp;<br />7) send you related information, including confirmations, invoices, technical notices, updates, security alerts, and support and administrative messages;&nbsp;<br />8) communicate with you about promotions, rewards, upcoming events, and other news about products and services offered by Rich Pleasure Resources&nbsp;and our selected partners;&nbsp;<br />9) enable you to communicate with other users; and&nbsp;<br />10) link or combine it with other information we get from third parties, to help understand your preferences and provide you with better services.&nbsp;</p>
<p>&nbsp;</p>
<h3>Disclosure of Your information</h3>
<p><br />Rich Pleasure Resources does not share your personal information except as approved by you or as described below:&nbsp;<br />Rich Pleasure Resources may engage other companies and individuals to perform services on our behalf. Example of these services include analyzing data and providing customer support. These agents and service providers may have access to your personal information in connection with the performance of services for Rich Pleasure Resources.&nbsp;<br />We may release your information as permitted by law, such as to comply with a subpoena, or when we believe that release is appropriate to comply with the law; investigate fraud, respond to a government request, enforce or apply our rights; or protect the rights, property, or safety of us or our users, or others. This includes exchanging information with other companies and organizations for fraud protection.&nbsp;</p>
<p>Rich Pleasure Resources may share your information in connection with any merger, sale of our assets, or a financing or acquisition of all or a portion of our business to another company. You will be notified via email and/or notice on our site of any change in ownership or users of your personal information.&nbsp;<br />We may share aggregate or anonymous information about you with advertisers, publishers, business partners, sponsors, and other third parties.&nbsp;</p>
<h3>Changes to the Policy</h3>
<p><br />We may update this privacy policy to reflect changes to our information practices. We encourage you to periodically review this page for the latest information on our privacy practices.&nbsp;</p>
<h3>Security</h3>
<p><br />Rich Pleasure Resources takes reasonable measures to protect your information from unauthorized access or against loss, misuse or alteration by third parties.&nbsp;<br />Although we make good faith efforts to store the information collected on the Service in a secure operating environment that is not available to the public, we cannot guarantee the absolute security of that information during its transmission or its storage on our systems. Further, while we attempt to ensure the integrity and security of our network and systems, we cannot guarantee that our security measures will prevent third-party "hackers" from illegally obtaining access to this information. We do not warrant or represent that your information will be protected against, loss, misuse, or alteration by third parties. No method of transmission over the Internet, or method of electronic storage, is 100% secure, however. Therefore, we cannot guarantee its absolute security.&nbsp;</p>
<h3>Access to Personal Information</h3>
<p><br />If your personal information changes, or if you no longer desire our service, you may correct, update, or delete inaccuracies by making the change within your account settings or by contacting us at richpleasure4u@gmail.com. We will respond to your access request within 30 days.&nbsp;</p>
<h3>Data Retention</h3>
<p><br />We will retain your information for as long as your account is active or as needed to provide you services. If you wish to cancel your account or request that we no longer use your information to provide you service. We will retain and use your information as necessary to comply with our legal obligations, resolve disputes, and enforce our agreements.&nbsp;</p>
<h3>Opting Out of Marketing</h3>
<p><br />You may opt-out of receiving promotional emails from us by following the instructions in those emails by emailing us. If you opt-out, we may still send you non-promotional emails, such as emails about your accounts or our ongoing business relations.&nbsp;</p>
<h3>International Transfer</h3>
<p><br />We may transfer information that we collect about you to affiliated entities, or to other third parties across borders and from your country or jurisdiction to other countries or jurisdictions around the world. Please note that these countries and jurisdictions may not have the same data protection laws as your own jurisdiction, and we take steps to ensure adequate safeguards are in place to enable transfer of information to elsewhere and the use and disclosure of information about you, including personal information, as described in this Policy.&nbsp;</p>
<p><br />Contact Information&nbsp;<br />Rich Pleasure Resources<br />No 17, Lorong 2C, Taman Alam Nyata, Seksyen 36, 41000 Shah Alam<br />If you have any questions about this Policy, please contact us at richpleasure4u@gmail.com</p>